---
- name: Block port 80 on system
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create a firewall
    gcp_compute_firewall:
        name: "kb-allow-ssh"
        ## Need to find a way to abstract this out also
        project: "kbenson-rh-summit-19"
        allowed:
          - ip_protocol: tcp
            ports:
            - '22'
        auth_kind: "serviceaccount"
        ## Need to find a way to abstract this out
        service_account_file: "kbenson-rh-summit-19-7dc89bed13a7.json"
        state: present