---
- name: Deploy a basic httpd vm
  hosts: tag_http-server
  tasks: 
   - name: Install httpd
     yum:
       name: httpd
       state: present
   - name: Add basic hello world file
     file:
       path: /var/www/html/index.html
       owner: apache
       group: apache
       mode: 0644
   - name: Add basic body to index file
     lineinfile:
       path: /var/www/html/index.html
       regex: "<body>Hello World!</body>"
       state: present
       owner: apache
       group: apache
       mode: 0644 
       state: present
   - name: Start httpd service
     service:
       name: httpd
       state: started
       enabled: yes