---
- name: Compute Engine Instance Examples
  hosts: localhost
  vars:
    gcp_project: "kbenson-rh-summit-19"
    gcp_cred_kind: "serviceaccount"
    gce_images_path: "projects/gce-uefi-images/global/images/"
    gce_distro: "centos-7-v20190326"
    gce_zone: "us-east1-b"
    gce_tags: 
      - http-server
    # Ansible Tower stores the GCE credentials in env variables
    gce_project: "{{ lookup('env','GCE_PROJECT') }}"
    gce_account_file: "{{ lookup('env','GCE_CREDENTIALS_FILE_PATH') }}"
  tasks:

    - name: Create an instance
      gcp_compute_instance:
        name: "{{username}}-{{ 60 | random }}"
        machine_type: "{{ instance_type }}"
        disks:
        - auto_delete: true
          boot: true
          initialize_params:
            disk_size_gb: "{{ disk_var | default(10)}}"
            source_image: projects/coreos-cloud/global/images/coreos-stable-2079-6-0-v20190617
        network_interfaces:
        - access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
        metadata: 
          istest: true
        zone: "{{ gce_zone }}"
        project: "{{gce_project}}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gce_account_file }}"
        state: present
        tags: 
          items: 
            "{{ gce_tags }}"
      register: output
    
    - debug:
        msg: "To access this system, run the following: ssh -i ~/.ssh/google_compute_engine kylebenson@{{ output.networkInterfaces[0].accessConfigs[0].natIP }}"   