---
- name: Compute Engine Instance Examples
  hosts: localhost
  vars:
    # service_account_email: "kbenson@redhat.com"
    # gcp_cred_file: "kbenson-rh-summit-19-7dc89bed13a7.json"
    # gcp_project: "kbenson-rh-summit-19"
    # gcp_cred_kind: "serviceaccount"
  tasks:

    - name: Create an instance
      gcp_compute_instance:
        name: "test-{{ 60 | random }}"
        machine_type: g1-small
        disks:
        - auto_delete: true
          boot: true
          initialize_params:
            disk_size_gb: "{{ disk_var | default(10)}}"
            source_image: projects/gce-uefi-images/global/images/centos-7-v20190326
        network_interfaces:
        - access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
        metadata:
        zone: us-central1-a
        # project: "{{ gcp_project }}"
        # auth_kind: "{{ gcp_cred_kind }}"
        # service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: output
    
    - debug:
        msg: "To access this system, run the following: ssh -i ~/.ssh/google_compute_engine kylebenson@{{ output.networkInterfaces[0].accessConfigs[0].natIP }}"   